### PR TITLE
bugfix: Clear button always clears all crashes

### LINKED ISSUE #44: Clear button always clears all crashes
There is a top level Clear button which clears all crashes - fine.

But when a particular app crash group is selected, there is still a Clear button in the menu. Tapping it also clears all crashes instead of just that app's crashes - not fine. It is unexpected UX.

### PR DESCRIPTION
**Pull request by kkoshin**
close #44

### CODE REVIEW

**Comment by opusforlife2** [comment]
@kkoshin What happened?

**Comment by kkoshin** [comment]
> @kkoshin What happened?

I found a better alternative: https://github.com/F0x1d/LogFox

No reason to fix this inactive app

**Comment by opusforlife2** [comment]
Oh. Does it monitor apps for crashes too? I thought it was a standard logcat app like Matlog.

**Comment by kkoshin** [comment]
> Oh. Does it monitor apps for crashes too? I thought it was a standard logcat app like Matlog.

Of course, it can monitor crash logs and manage blocked apps through a blacklist.

Also, I should add that it supports Shizuku authorization.

For more details, just install it from F-Droid and give it a try yourself

**Pull request closed without merging**
