### PR TITLE
Use new api for force english language

### PR DESCRIPTION
**Pull request by kaozaza2**
Reference:
https://developer.android.com/about/versions/13/features/app-languages

### CODE REVIEW

**Comment by TacoTheDank** [comment]
?

**Comment by kaozaza2** [comment]
Sorry, accident delete branch.

**Comment by kaozaza2** [comment]
Can merge it?

**Comment by TacoTheDank** [comment]
I've been busy for a little bit. I'll get to it when I can.

**Comment by TacoTheDank** [comment]
I do not wish to use pre-release library versions, so this will have to sit until that AppCompat version is stable.

**Comment by xnumad** [comment]
This will probably also properly apply the language to notifications (they're currently still in system language despite "Force English app language") 👍

**Review by Akhenaton27 — APPROVED** [review]
Nix

**Pull request closed without merging**
